In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent = ['the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
voc_size = 10000

In [6]:
### One Hot Representation
one_hot_repr = [one_hot(words,voc_size)for words in sent]
print(one_hot_repr)

[[8272, 8115, 1927, 1787], [8272, 8115, 1927, 548], [8272, 5972, 1927, 3272], [1392, 8229, 3187, 9516, 3950], [1392, 8229, 3187, 9516, 5977], [3547, 8272, 8196, 1927, 8710], [4156, 7187, 8751, 9516]]


In [7]:
### Word embedding Representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 8272 8115 1927 1787]
 [   0    0    0    0 8272 8115 1927  548]
 [   0    0    0    0 8272 5972 1927 3272]
 [   0    0    0 1392 8229 3187 9516 3950]
 [   0    0    0 1392 8229 3187 9516 5977]
 [   0    0    0 3547 8272 8196 1927 8710]
 [   0    0    0    0 4156 7187 8751 9516]]


In [10]:
# feature representation
dim =10

In [11]:
model=Sequential()
model.add(Embedding(voc_size, dim, input_length=sent_length))
model.compile('adam','mse')

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [14]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 39ms/step


array([[-0.02289206,  0.00163875, -0.03978343,  0.00800136, -0.00142384,
         0.03361105, -0.02664693,  0.00494026,  0.00348867, -0.03000002],
       [-0.02289206,  0.00163875, -0.03978343,  0.00800136, -0.00142384,
         0.03361105, -0.02664693,  0.00494026,  0.00348867, -0.03000002],
       [-0.02289206,  0.00163875, -0.03978343,  0.00800136, -0.00142384,
         0.03361105, -0.02664693,  0.00494026,  0.00348867, -0.03000002],
       [-0.02289206,  0.00163875, -0.03978343,  0.00800136, -0.00142384,
         0.03361105, -0.02664693,  0.00494026,  0.00348867, -0.03000002],
       [-0.0391834 , -0.01554034,  0.00169679,  0.03289877,  0.03629196,
         0.04516578,  0.00675603,  0.02441603, -0.0274558 ,  0.04468321],
       [-0.0431464 ,  0.01733914,  0.03504554,  0.02813068, -0.00306387,
        -0.03906639, -0.01956211, -0.03054952,  0.04285263, -0.02585361],
       [ 0.04305379,  0.02563032,  0.00056088,  0.04757272,  0.04816006,
         0.04118819, -0.0153432 , -0.04328331